[project]
name = "wc-pool-2026"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "click",
    "numpy",
    "pandas",
    "pandas-stubs~=3.0.3",
    "python-dotenv",
    "requests",
    "scipy",
    "tqdm",
]

[project.scripts]
calculate-first-prize-probs = "wc_pool_2026.calculate_first_prize_probs:main"
calculate-third-prize-monte-carlo = "wc_pool_2026.calculate_third_prize_monte_carlo:main"
calculate-third-prize-odds = "wc_pool_2026.calculate_third_prize_odds:main"
fetch-world-cup-match-odds-raw = "wc_pool_2026.fetch_world_cup_match_odds_raw:main"
fetch-world-cup-results = "wc_pool_2026.fetch_world_cup_results:main"
fetch-world-cup-winner-odds-raw = "wc_pool_2026.fetch_world_cup_winner_odds_raw:main"
list-odds-api-sports = "wc_pool_2026.the_odds_api:main"
transform-world-cup-match-odds = "wc_pool_2026.transform_world_cup_match_odds:main"
transform-world-cup-results = "wc_pool_2026.transform_world_cup_results:main"
transform-world-cup-winner-odds = "wc_pool_2026.transform_world_cup_winner_odds:main"

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
